// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOX_UGwT6F6hUcbjwrZBxqlr5xzSh4al0',
    appId: '1:607300927534:web:d2b9d3453a2ef989d99fbf',
    messagingSenderId: '607300927534',
    projectId: 'urbanlink-1783e',
    authDomain: 'urbanlink-1783e.firebaseapp.com',
    storageBucket: 'urbanlink-1783e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnutM6RxyB2_bUvQVdlEm2ojp9Sg6lk-w',
    appId: '1:607300927534:android:6df8b27b24458b23d99fbf',
    messagingSenderId: '607300927534',
    projectId: 'urbanlink-1783e',
    storageBucket: 'urbanlink-1783e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzQBh_9OkBvDigJ023Auhv_A7kVHPkY0',
    appId: '1:607300927534:ios:ad84cc798a24d11ed99fbf',
    messagingSenderId: '607300927534',
    projectId: 'urbanlink-1783e',
    storageBucket: 'urbanlink-1783e.appspot.com',
    iosClientId:
        '607300927534-ifoc884qqfmka3kgi7f9e675ito85kd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanlinkProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnzQBh_9OkBvDigJ023Auhv_A7kVHPkY0',
    appId: '1:607300927534:ios:ad84cc798a24d11ed99fbf',
    messagingSenderId: '607300927534',
    projectId: 'urbanlink-1783e',
    storageBucket: 'urbanlink-1783e.appspot.com',
    iosClientId:
        '607300927534-ifoc884qqfmka3kgi7f9e675ito85kd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanlinkProject',
  );
}
